server:
  port: 3001
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: df8532dd214290499fc71ddcb7cfa3c897e55ce6cdc56b88a658cc0cd5ba73c4
    url: jdbc:postgresql://ec2-35-170-21-76.compute-1.amazonaws.com/d6ttl6lge34a59
    username: kyilaagamnofqd
#    url: jdbc:postgresql://postgresql:5432/lifeCalendar
#    username: postgres
#    password: iamadmin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: noupsovan18@gmail.com
    password: oyzzjzhjctysmynv

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000